### ISSUE TITLE
Feature request: Matrix notifications

### ISSUE THREAD

**Issue by dbrgn** [containrrr/shoutrrr#112]
It would be nice if a Matrix channel could be used as notification target.

I don't actually know what would be required to achieve this, as I'm neither familiar with Matrix internals nor with Go. But as a user of Watchtower, I'd appreciate support for it 🙂

**Comment by piksel** [comment]
![image](https://user-images.githubusercontent.com/807383/104192079-a2157780-541e-11eb-9495-49b057d789e0.png)

**Comment by dbrgn** [comment]
Oh wow, that was fast! Thank you! 😃

**Comment by piksel** [comment]
@RedJohn14 You can try it in the [feat/matrix](https://github.com/containrrr/shoutrrr/tree/feat/matrix) branch which both has the implementation and the updated docs.
It should work, but it's only really been tested/looked at by a single developer (who doesn't use Matrix outside of just testing this).

**Comment by RedJohn14** [comment]
> @RedJohn14 You can try it in the [feat/matrix](https://github.com/containrrr/shoutrrr/tree/feat/matrix) branch which both has the implementation and the updated docs.
> It should work, but it's only really been tested/looked at by a single developer (who doesn't use Matrix outside of just testing this).

Thanks for fast reply, is there any docker-compose? I want to use this with Watchtower to notify me if docker container updates are available.

Which container I must use it? (shoutrrr and watchtower container or is shourtrrr intetegrated in watchtower container?)

**Comment by piksel** [comment]
Yeah, that's not the easiest to accomplish unfortunately. Shoutrrr is built into watchtower statically when compiled, so you would have to build your own watchtower binary and docker image. It should be included in the next shoutrrr-release though, so you should be able to try it using `watchtower:latest-dev` soonish. But it's all very uncertain as all work on shoutrrr and watchtower is done on spare time, so it's hard to give estimates.

**Comment by RedJohn14** [comment]
> Yeah, that's not the easiest to accomplish unfortunately. Shoutrrr is built into watchtower statically when compiled, so you would have to build your own watchtower binary and docker image. It should be included in the next shoutrrr-release though, so you should be able to try it using `watchtower:latest-dev` soonish. But it's all very uncertain as all work on shoutrrr and watchtower is done on spare time, so it's hard to give estimates.

Thanks, again for fast reply. In `watchtower:latest-dev` is no Shoutrrr with matrix support, right? So I must wait for the next release or? 

Or is there some other way to get watchtower working with matrix notifications?

**Comment by piksel** [comment]
Well, building it yourself, but that takes some getting into go dependencies and building docker images. There is also a lot of matrix bridges, so perhaps using one of those with another service, like discord might work? Not something I have tried though.
