### ISSUE TITLE
Feature request: use an environment variable for the URL

### ISSUE THREAD

**Issue by rubiojr** [containrrr/shoutrrr#12]
It'd be nice to be able to use an environment variable like `SHOUTRRR_URL` or something similar instead of typing it.

I'm suggesting this because command line arguments are logged by Bash in the history file, visible in the process list, etc.

Had a quick look at the source, looks like it could be done without breaking backwards compatibility (assuming that's important now) if we detect the first argument isn't a valid URL so we can interpret it a s the message instead?

**Comment by rubiojr** [comment]
To clarify, I'm talking about the CLI version of `shoutrrr` here.

**Comment by simskij** [comment]
Great idea! 👏🏼 Probably most flags should be available as env vars as well. One idea I've been toying with is moving the whole CLI over from the built-in flags package to cobra and viper, which would solve this issue.

Would you be up for having a look at it? I'd be happy to review and assist you in getting it merged.

**Comment by simskij** [comment]
I agree with you on that it likely should not affect backward compatibility.

**Comment by simskij** [comment]
I'll have a stab at this (any day now).

**Comment by piksel** [comment]
This is how we do the integration tests btw:
https://github.com/containrrr/shoutrrr/blob/77a21897b23881d9d3b98cac9f962763da70775a/pkg/services/telegram/telegram_test.go#L29
