### ISSUE TITLE
Microsoft Teams connector webhook URL format changed

### ISSUE THREAD

**Issue by kevinlul** [containrrr/shoutrrr#138]
![image](https://user-images.githubusercontent.com/6320810/107651016-0eb5a900-6c4d-11eb-9422-c86f39608427.png)

This causes `teams://` URLs to fail as well as directly pasting the webhook URL for the Watchtower Teams integration, since it tries to parse the URL and use shoutrrr anyway.

**Comment by piksel** [comment]
This is fixed in v0.4.0 and should be included in the next watchtower release.

**Comment by papanito** [comment]
I guess docu should be updated as well: https://github.com/containrrr/shoutrrr/blob/main/docs/services/overview.md

**Comment by papanito** [comment]
> Yeah, and I just noticed that they actually explain what the fields are above, documentation I wasn't able to find anywhere before.

I actually don't find this documentation either.

**Comment by piksel** [comment]
This was addressed in #167, but the docs still contain some incorrect information:
https://containrrr.dev/shoutrrr/services/teams/

Keeping this open until it's fixed.

**Comment by LanJosh** [comment]
> > Yeah, and I just noticed that they actually explain what the fields are above, documentation I wasn't able to find anywhere before.
> 
> I actually don't find this documentation either.

I can't seem to find this documentation either, what is the <tName> field supposed to be?

**Comment by piksel** [comment]
@LanJosh `host`. It's in the top *Attention* box in the docs:
https://containrrr.dev/shoutrrr/latest/services/teams/

If you are referring to how to get it, it's the hostname that your teams webhook URL starts with: `xxxxxx.webhook.office.com`

You can follow [the guide in the teams docs](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#create-incoming-webhook-1) to create a new one if you don't have one with the correct host.

**Comment by igorcezar** [comment]
Since the webhook URL format changed, shouldn't this line also be able to set /webhookb2/?

https://github.com/containrrr/shoutrrr/blob/23170b836d31a2231011472b6e8a91bf98bf6b26/pkg/services/teams/teams_config.go#L106

It doesn't work for new URL format because it will build the url as `https://<tName>.webhook.office.com/webhook/token...`, which doesn't exist.

**Comment by piksel** [comment]
@igorcezar both the `webhookb2` and `webhook` URLs worked in the integration tests (that's why it wasn't caught earlier). nevertheless, it was wrong and has been fixed in #188

**Comment by wargamez** [comment]
Will there be a new release any time soon that fixes this?
