### ISSUE TITLE
Telegram doesn’t work with documented format

### ISSUE THREAD

**Issue by mbrandau** [containrrr/shoutrrr#16]
The format that works is `telegram://<api-token>@telegram?channels=<channel-a>,<channel-b>,...`.
Should the documentation be changed accordingly or should the code be changed to use the format as described in the documentation?

**Comment by mbrandau** [comment]
Same goes for Discord: the working format is `discord://token@channel` instead of `discord://channel/token`

**Comment by simskij** [comment]
> The format that works is `telegram://<api-token>@telegram?channels=<channel-a>,<channel-b>,...`.
> Should the documentation be changed accordingly or should the code be changed to use the format as described in the documentation?

The docs should definitely be changed.

> Same goes for Discord: the working format is `discord://token@channel` instead of `discord://channel/token`

Dito, docs change rather than changing the code.

**Comment by mbrandau** [comment]
👍 I already updated the documentation in #18
