### ISSUE TITLE
Documentation for Slack is virtually non-existent and confusing

### ISSUE THREAD

**Issue by millermarkj** [containrrr/shoutrrr#165]
I started a thread on the Discussions board but this seems to be more suited for Issues. 

I was only able to fully determine the expected format of a Slack connection string after noting Issue 90 (https://github.com/containrrr/shoutrrr/issues/90), which has been closed but not resolved (the documentation is still woefully lacking). 

It appears that a Slack connection string needs to be in the format of a slack webhook, _not_ an API key or token. So theoretically, the format would be:

    slack://A1B234CDE/Z12345Y123Q/ABCD1lmnoPqr0tuVwXYz

---

Edit: This is related to the application I'm using which integrates shoutrrr, not shoutrrr itself, so I've struck it.
~~Unfortunately this doesn't seem to work:~~

~~`# curl -X POST http://localhost:8080/api/health/notify`~~
~~`{"errors":["thumb_url is not a valid config key [color title]"],"success":false}`~~

---

This is still essentially undocumented and should be fixed. At a bare minimum, the documentation should include a link to the "Getting Started" page for Slack webhooks: https://api.slack.com/messaging/webhooks

On top of this, the generator for Slack is broken and throws an error on any input to the "token" field:
```
user@hostname:/opt/svc/scrutiny$ docker run --rm --interactive containrrr/shoutrrr generate slack
Generating URL for slack using basic generator
Enter the configuration values as prompted

BotName: botname
Color: blue
Title: botname
Token:
Field Token is required!

Token: 0

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/containrrr/shoutrrr/pkg/services/slack.(*Config).getURL(0xc0000b2aa0, 0xadd240, 0xc000097080, 0xc0000b2aa0)
        /home/runner/work/shoutrrr/shoutrrr/pkg/services/slack/slack_config.go:37 +0x35d
github.com/containrrr/shoutrrr/pkg/services/slack.(*Config).GetURL(0xc0000b2aa0, 0xc00000e018)
        /home/runner/work/shoutrrr/shoutrrr/pkg/services/slack/slack_config.go:24 +0xb9
github.com/containrrr/shoutrrr/cli/cmd/generate.Run(0xe6bf80, 0xc00006d4b0, 0x1, 0x1)
        /home/runner/work/shoutrrr/shoutrrr/cli/cmd/generate/generate.go:127 +0x82f
github.com/spf13/cobra.(*Command).execute(0xe6bf80, 0xc00006d490, 0x1, 0x1, 0xe6bf80, 0xc00006d490)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe6c760, 0x0, 0x0, 0xc000098058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
        /home/runner/work/shoutrrr/shoutrrr/cli/main.go:26 +0x2d
```

**Comment by piksel** [comment]
Yeah, the slack service is not documented at all. The format `slack://A1B234CDE/Z12345Y123Q/ABCD1lmnoPqr0tuVwXYz` should be correct.
The reason that `shoutrrr generate` crashes is because the token is stored internally as an array and must be entered as:
```
Token: A1B234CDE,Z12345Y123Q,ABCD1lmnoPqr0tuVwXYz
```
It's not very intuitive and the only reason it's that way is because of technical limitations in the configuration API. Those limitations are now gone and we could add a custom deserializer for the token field that handles various formats and gives good feedback.

**Comment by piksel** [comment]
Hope that this is more helpful:
https://containrrr.dev/shoutrrr/services/slack/
