### ISSUE TITLE
Service URL format documentation

### ISSUE THREAD

**Issue by mbrandau** [containrrr/shoutrrr#17]
The current documentation doesn’t really allow for more elaborate explanations. For example the SMTP service would need a more thorough documentation. (currently it isn’t listed)

My suggestion would be to format the README something along the lines like this:

### Service URLs

To make it easy and streamlined to consume shoutrrr regardless of the notification service you want to use,
we've implemented a notification service url schema. To send notifications, instantiate the ShoutrrrrClient using one of
the service urls below.

| Service | Format |
| - | - |
| [SMTP](#smtp-service) | `smtp://username:password@host:port/?fromAddress=<fromAddress>&toAddresses=<addr1@host.com>,<addr2@other.com>` |
| [Discord](#discord-service) | `discord://channel/token` |
| Pushover | `pushover://token/user/device` |
| Slack | `slack://token-a/token-b/token-c`<br/>`slack://botname/token-a/token-b/token-c` |
| Teams | `teams://token-a/token-b/token-c` |
| Telegram | `telegram://api-token/channel`<br/>`telegram://api-token/channel-a/channel-b/channel-c/...` |
| Gotify | `gotify://gotify-host/token` |
| Pushbullet | `pushbullet://api-token`<br/>`pushbullet://api-token/device/#channel/e@mail.com`

#### SMTP service

Format: `smtp://<username>:<password>@<host>:<port>/?fromAddress=<fromAddress>&toAddresses=<addr1@host.com>,<addr2@other.com>`

##### Additional query parameters

| Key | Type | Default | Value |
| - | - | - | - |
| subject | `string` | `null` | Subject of the email |
| startTls | `boolean` | `true` | attempt to use SMTP StartTLS encryption |
| ... |

#### Discord service

...

**Comment by simskij** [comment]
I like this idea! Maybe it should even use mkdocs so the readme dont become 4k lines long? 😅

**Comment by mbrandau** [comment]
Should’ve thought about mkdocs 😄 I’ll do some copy and pasting!

**Comment by piksel** [comment]
Things were left (mostly by me) in kind of a mess unfortunately.
