### ISSUE TITLE
Discord custom avatar not working

### ISSUE THREAD

**Issue by martadinata666** [containrrr/shoutrrr#171]
As per shoutrr [discord notification](https://containrrr.dev/shoutrrr/services/discord/) manual to change default avatar ```AvatarURL``` used. But watchtower container throw error.

My WATCHTOWER_NOTIFICATION_URL
```
"discord://sometoken@some-webhook-id?AvatarURL=the-img-url.png&username=Watchtower&splitlines=no"
```

No caps lock
```
 level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: avatarurl is not a valid config key [avatar color colordebug colorerror colorinfo colorwarn splitlines title username]\n"
```

Caps lock
```
 level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: AvatarURL is not a valid config key [avatar color colordebug colorerror colorinfo colorwarn splitlines title username
```

**Comment by piksel** [comment]
It must have been accidently changed in the development branch (and hence the documentation).
Simply use `avatar` (casing does not matter).

**Comment by martadinata666** [comment]
using ```avatar``` doesn't throw error, but seems the image URL didn't parsed? As the icon stay the same as discord default icon.

**Comment by piksel** [comment]
@martadinata666 No, I just confirmed it as being broken in v0.4.4. Sorry about that. Working on a fix!
