### ISSUE TITLE
[Telegram] Notification 400 Bad Request when running from cron

### ISSUE THREAD

**Issue by Kwbmm** [containrrr/shoutrrr#181]
Hello!

I'm experiencing the following error when trying to send a telegram notification through the `shoutrrr` docker container. 

```
Error: failed to send notification to "CHANNEL_ID", response status code 400 Bad Request
```

I have a shell function that looks like this

```sh
notify() {
  local title="$1"
  local body="$2"
  local msg=$(echo -e "*$title*\n\n$body")
  docker run --rm containrrr/shoutrrr send -u 'telegram://TOKEN@telegram?channels=CHANNEL_ID&parseMode=markDownv2' --message "$msg"
}
```

This function is saved into a backup script that I run every 5 days through cron (crontab).

```
0 4 */5 * * /home/pi/homeserver/backup.sh
```

Running the backup script manually (i.e. `./backup.sh`) works fine and I get notified correctly on telegram. When the above function is run through crontab, it fails with the `400 bad request` error.

I have absolutely no clue on what's wrong with that. Clearly it's neither a permission nor a syntax error, because the container is created (i.e. permissions ok) and the message can be sent if the script is run manually (i.e. no syntax error).

EDIT: Forgot to mention. Docker image is latest `linux/arm`

**Comment by piksel** [comment]
I suspect the text format. The markdown parser for telegram is REALLY picky. You have to escape a lot of characters etc.

**Comment by Kwbmm** [comment]
I can try that, but how do you explain that the same code works if I launch the script manually?

**Comment by piksel** [comment]
Are you sending the exact same message?
Here is the reference docs:
https://core.telegram.org/bots/api#sendmessage

I would probably use HTML instead since it's much easier to escape for (only tags):
```bash
local esc_title=${title//</&lt;}
esc_title=${esc_title//>/&gt;}
local esc_body=${body//</&lt;}
esc_body=${esc_body//>/&gt;}

local msg=$(echo -e "<i>$esc_title</i>\n\n$esc_body")
docker run --rm containrrr/shoutrrr send -u 'telegram://TOKEN@telegram?channels=CHANNEL_ID&parseMode=HTML' --message "$msg"
```

**Comment by Kwbmm** [comment]
Yes exact same message. It's part of a script run by crontab.

I'll try the HTML parser, I didn't know I could use that!

**Comment by Kwbmm** [comment]
Looks like the HTML parsers works better! I don't get the error anymore!
