### ISSUE TITLE
Initializing services with a Custom URL crashes when no logger has been provided

### ISSUE THREAD

**Issue by igorcezar** [containrrr/shoutrrr#186]
I've tried to use a custom URL (#125) for teams notification using Kured v1.7.0, but got the error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14747fb]

goroutine 26 [running]:
github.com/containrrr/shoutrrr/pkg/router.(*ServiceRouter).initService(0x2330de0, 0x7ffc102cdcc0, 0xd3, 0x30, 0xc000042870, 0x30, 0x1)
	/home/runner/go/pkg/mod/github.com/containrrr/shoutrrr@v0.4.4/pkg/router/router.go:189 +0x17b
github.com/containrrr/shoutrrr/pkg/router.(*ServiceRouter).Locate(...)
	/home/runner/go/pkg/mod/github.com/containrrr/shoutrrr@v0.4.4/pkg/router/router.go:238
github.com/containrrr/shoutrrr.Send(0x7ffc102cdcc0, 0xd3, 0xc000042870, 0x30, 0x1, 0xc000042870)
	/home/runner/go/pkg/mod/github.com/containrrr/shoutrrr@v0.4.4/shoutrrr.go:17 +0x45
main.drain(0xc000015080, 0xc0006f8000)
	/home/runner/work/kured/kured/cmd/kured/main.go:351 +0x6b7
main.rebootAsRequired(0xc00004002e, 0xc, 0xc0002061e0, 0x5, 0x6, 0xc000206180, 0x6, 0x6, 0xc000326240, 0x22ecb25c000, ...)
	/home/runner/work/kured/kured/cmd/kured/main.go:569 +0x676
created by main.root
	/home/runner/work/kured/kured/cmd/kured/main.go:644 +0xc05
```

The custom URL used:
`--notify-url=teams+https://<tName>.webhook.office.com/webhookb2/group@tenant/IncomingWebhook//altid/groupowner`

The problem seems to be here:
https://github.com/containrrr/shoutrrr/blob/23170b836d31a2231011472b6e8a91bf98bf6b26/pkg/router/router.go#L189

Maybe router.logger is not initialized when kured calls it?

**Comment by piksel** [comment]
Indeed, good call!

The `defaultRouter` (the helper singleton instance used by kured) is not initialized with a logger:
https://github.com/containrrr/shoutrrr/blob/23170b836d31a2231011472b6e8a91bf98bf6b26/shoutrrr.go#L8

This is handled inside each service (by not logging), but the router itself has no nil guards.

**Comment by igorcezar** [comment]
Great! 💯  
Thanks for the quick response!

Any idea when v0.5.0 is going to be released?

**Comment by piksel** [comment]
The overall goals for v0.5 has been met, so as soon as I find the time 😅

**Comment by igorcezar** [comment]
No worries, just curious! haha
