### ISSUE TITLE
Add notification types

### ISSUE THREAD

**Issue by simskij** [containrrr/shoutrrr#2]
It should be possible to post notifications to any of the following services:
Priority in descending order.

## Services
- [x] Discord
- [x] Gotify
- [x] Hangouts
- [x] IFTTT
- [x] Local logs
- [x] MatterMost
- [x] Pushbullet
- [x] Pushover
- [x] Slack
- [x] Email
- [x] Microsoft Teams
- [x] Telegram
- [x] Zulip Chat
- [x] Join
- [ ] Twitter
- [ ] Gitter
- [ ] Facebook
- [ ] XMPP (#6)
- [ ] Rocket.Chat
- [ ] Generic Webhook (other) - how?

## Candidates for review
- [Opsgenie](https://www.opsgenie.com/)
- [VictorOps](https://victorops.com/)
- [PagerDuty](https://www.pagerduty.com/)

## Wont fix
* ~HipChat~

### 24 June, 2019
IFTTT webhook service done.

### 9 June, 2019
Hipchat is discontinued and will be replaced by slack according to [this page](https://www.atlassian.com/partnerships/slack), so hipchat will not be implemented. Unsure whether Google Hangouts will continue to be a maintained product. Until someone wants it we'll just leave it out.

**Comment by crobibero** [comment]
Possible to also add [Gotify](https://gotify.net/)?

**Comment by alexanderadam** [comment]
Ah, sorry: I saw this issue too late. Should I close #6 to move it into #2?

IMHO it would be easier to track support for those services if they would have a dedicated issue, wouldn't it?

Generic Webhook would be nice indeed. Or, if it's too difficult: [a Sentry webhook](https://docs.sentry.io/api/projects/post-project-service-hooks/) would be nice.

**Comment by simskij** [comment]
> Ah, sorry: I saw this issue too late. Should I close #6 to move it into #2?
> 
> IMHO it would be easier to track support for those services if they would have a dedicated issue, wouldn't it?
> 
> Generic Webhook would be nice indeed. Or, if it's too difficult: [a Sentry webhook](https://docs.sentry.io/api/projects/post-project-service-hooks/) would be nice.

Nah, it's ok. Let's keep it as is. 👍 Yeah, sentry would be nice indeed. However, as notifications might have other levels than errors (like info or debug) that might get weird. Of course, you could always mute the notifications you dont want in sentry.

Does that make sense?

**Comment by alexanderadam** [comment]
> However, as notifications might have other levels than errors (like info or debug) that might get weird.

Sentry is also able to do [release and deploy tracking](https://docs.sentry.io/cli/releases/) which would exactly be the reason why I would use it together with [watchtower](https://github.com/containrrr/watchtower).

**Comment by simskij** [comment]
> Sentry is also able to do [release](https://docs.sentry.io/workflow/releases/?platform=browser#using-the-api) and [deploy tracking](https://docs.sentry.io/api/releases/post-release-deploys/) which would exactly be the reason why I would use it together with [watchtower](https://github.com/containrrr/watchtower) (because watchtower is more or less about deploying newly released Docker images, right?).

Ooooh, I like how You think! And yes, that's exactly what it's about :D

**Comment by lukasmrtvy** [comment]
What about rocketchat, gitter, mattermost and matrix as opensource alternatives to slack ? Thanks

**Comment by simskij** [comment]
> What about rocketchat, gitter, mattermost and matrix as opensource alternatives to slack ? Thanks

Feel free to create a pull request on whatever notification service you desire! 😅 I'd be happy to provide reviews and helping you getting it merged! 👍🏻

**Comment by lukwil** [comment]
I think I will try to create a Gitter integration.
I hope I am able to create a PR in the next couple of days.

**Comment by amirkrasnic** [comment]
I am currently working on a PR for Mattermost.

**Comment by simskij** [comment]
@all-contributors add @simskij for code, docs, maintenance

**Comment by ajayjohn** [comment]
Could you please consider adding Join to your list of notification targets? Join is built by the developer of Tasker on Android and serves as a gateway to achieve quite complex automation flows on Android devices.
https://joaoapps.com/join/api/

**Comment by simskij** [comment]
> Could you please consider adding Join to your list of notification targets? Join is built by the developer of Tasker on Android and serves as a gateway to achieve quite complex automation flows on Android devices.
> https://joaoapps.com/join/api/

Done by @piksel in #43. Feel free to try it out :)

**Comment by vajonam** [comment]
Any word on the generic webhook?

**Comment by kjenneycloudhealth** [comment]
Pagerduty notification would be very helpful.

**Comment by kjenneycloudhealth** [comment]
Also, how does the local logs notification type work? I don't see it in any of the documentation.

**Comment by piksel** [comment]
@kjenneycloudhealth No, you're right it should probably be mentioned. I guess the reason for it not being there is that there is no configuration for it.
The only thing it does is write the notification message to the `Router`s logger.

**Comment by RaminMT** [comment]
Hi
Thanks for your nice library
How about webhook support, I didn't seen conversation about it

**Comment by piksel** [comment]
@RaminMT well, if you mean a generic webhook service, it's a bit complicated. Most webhooks need a specific payload to be sent to them. It's one of the main purposes of the templates that services can use.
If you are consuming shoutrrr "directly" without exposing it's URLs to the end user to configure, it's pretty trivial, so I guess I should just implement that first. 

Tracking this in #97 (Also @vajonam)

**Comment by simskij** [comment]
Closing this issue as we've implemented the majority of what we wanted to add.
If any other services are needed, please open a separate issue. Pull requests adding new services are welcome as well, as you probably know the service you'd like to use better than we do. 👍

**Comment by Somnius** [comment]
Any chance about XMPP (https://github.com/containrrr/shoutrrr/issues/6) ?
