### ISSUE TITLE
Emails flagged as spam

### ISSUE THREAD

**Issue by danielfomin96** [containrrr/shoutrrr#200]
**Describe the bug**

All emails that watchtower sends are marked as spam on my email server. Both services run on the same machine.

**To Reproduce**

1. Start watchtower container
2. Receive startup email
3. Email is in Spam folder

**Expected behavior**

Email should not be marked as spam

**Screenshots**

```
X-Spam-Flag: YES
X-Spam-Score: 7.625
X-Spam-Level: *******
X-Spam-Status: Yes, score=7.625 tagged_above=2 required=5
	tests=[BOGUS_MIME_VERSION=3.187, DKIM_INVALID=0.1, DKIM_SIGNED=0.1,
	FROM_SUSPICIOUS_NTLD=0.499, FROM_SUSPICIOUS_NTLD_FP=1.6,
	MISSING_MID=0.14, NO_RECEIVED=-0.001, NO_RELAYS=-0.001,
	PDS_OTHER_BAD_TLD=2, URIBL_BLOCKED=0.001]
	autolearn=no autolearn_force=no
[...]
From: Watchtower <no-reply@example.com>
Content-Type: text/plain; charset="UTF-8"
MIME-version: 1.0;
[...]
```
**Environment**

 - Platform: Ubuntu 20.10
 - Docker version: 20.10.2

**Comment by piksel** [comment]
> `BOGUS_MIME_VERSION=3.187`

Yeah, the `MIME-Version` header contains a extra `;` which shouldn't be there. I have no idea why that would be an indication of spaminess though...

The spam report from Mailtrap from shoutrrr integration tests show an almost perfect score:
![image](https://user-images.githubusercontent.com/807383/132044893-fcbbba62-d5fb-4f18-8d59-c2453dc70424.png)

**Comment by danielfomin96** [comment]
Would it be possible to fix the Mime-Version field?

**Comment by danielfomin96** [comment]
Thank you very much.
