### ISSUE TITLE
Priority for Pushover is not working

### ISSUE THREAD

**Issue by OliverHi** [containrrr/shoutrrr#204]
I am using shoutrrr with Watchtower to send notification via Pushover to my phone. I am looking to lower the priority level so that it does not buzz every time. According to the documentation a priority of -1 should be quiet.
I am trying to send that priority via a docker compose env variable like:
```
environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:${PO_TOKEN}@${PO_USERKEY}/?priority=-1
```
but the notifications are still not silent. Am I missing something here?

**Comment by piksel** [comment]
Indeed. Priorities lower than 0 is just ignored for some reason...
https://github.com/containrrr/shoutrrr/blob/29510980008bd85fc0016c0caa00ee17b105b1cd/pkg/services/pushover/pushover.go#L54-L56
