### ISSUE TITLE
Suggestion: Telegram Channel ID Documentation

### ISSUE THREAD

**Issue by J0n4t4n** [containrrr/shoutrrr#223]
I was setting up Watchtower with the shoutrrr notification type to send notifications to a Telegram channel.

I created a Telegram Bot, a Telegram Channel and made the Bot a Channel Administrator.
I was then struggling to figure out how to find the Channel ID, I tried #120, but the part after t.me/ didn't work.
After a lot of searching I found these instructions: https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35?permalink_comment_id=3611823#gistcomment-3611823

I think the Telegram documentation should include instructions on how to figure out a channel ID, maybe using the "Json Dump Bot" method.
So:
- Create a Channel
- Manually post a message
- Forward that message to "Json Dump Bot"
- message.forward_from_chat.id will contain the Channel ID

**Comment by piksel** [comment]
Yeah, the channel "name" can be used if you prefix it, but that seems to be missing from the docs. There is also a generator that helps with configuring telegram, which isn't mentioned either.

**Comment by davtur19** [comment]
Alternatively you could also use your chat ID/user ID (message.from.id on @jsondumpbot) instead of the channel ID; I find it more convenient to have messages sent in private chat with the bot than a channel.
Remember to start the bot, otherwise it will be impossible for the bot to send you messages.

**Comment by J0n4t4n** [comment]
> Yeah, the channel "name" can be used if you prefix it, but that seems to be missing from the docs. There is also a generator that helps with configuring telegram, which isn't mentioned either.

Ah, interesting. Yeah some documentation improvements seem to be needed.

> Alternatively you could also use your chat ID/user ID (message.from.id on @jsondumpbot) instead of the channel ID; I find it more convenient to have messages sent in private chat with the bot than a channel.
> 
> Remember to start the bot, otherwise it will be impossible for the bot to send you messages.

Yeah, for me I wanted it to be a channel specifically, but that's of course also an option.

**Comment by azoller1** [comment]
Omg yes. I literally could not understand how to use telegram. @jsondumpbot helped me finally get it to work. Thanks.

**Comment by piksel** [comment]
Yeah, I did update the docs, but I have not made a release yet so it's still under `dev`:
https://containrrr.dev/shoutrrr/dev/services/telegram/#identifying_the_target_chatschannels

I will make a new release as soon as I get time. Sorry.

**Comment by piksel** [comment]
Ineed, to get the ID for any type of chat, you can just forward a message from that chat to `@jsondumpbot` and it's reply find this part:
```
    "forward_from_chat": {
      "id": -1002737640605,
```
The Chat ID would then be `-1002737640605`.

I will add this information as well to the docs.

**Comment by piksel** [comment]
[Docs](https://containrrr.dev/shoutrrr/dev/services/telegram/#asking_shoutrrrbot) were updated in #250 along with the deployment of a specialized bot for this purpose.

> Since neither `@JsonDumpBot`, nor `@UserInfoBot` could help getting the Chat ID for group chats, I wrote a bot specifically for this purpose. It can be reached at [@shoutrrrbot](https://t.me/shoutrrrbot). Updated the docs to point to it instead.

_Originally posted by @piksel in https://github.com/containrrr/shoutrrr/issues/250#issuecomment-1139506206_
