### ISSUE TITLE
Teams documentation a bit confusing

### ISSUE THREAD

**Issue by JoeIzzard** [containrrr/shoutrrr#228]
I am trying to figure out how to configure Teams integration with a service that uses shoutrrr but the shoutrrr docs are a bit confusing.

In the services overview, it lists the format as:

`teams://tokenA/tokenB/tokenC`

But then on the actual Teams page it lists a different format of:

`teams://group@tennat/altId/groupOwner?host=example.webhook.office.com`

It then tells me how to extract my tokens, but no where in that format does it appear to use them?

Not sure if something was missed when the format changed or if I'm just missing something completely?

**Comment by piksel** [comment]
Yeah, not sure why the docs hasn't been updated, but the `dev` version shows the extract guidelines that matches the URL (but the overview still uses the old A/B/C names):
https://containrrr.dev/shoutrrr/dev/services/teams/

The overview should be fixed, and the docs for 0.5 should be updated.

**Comment by JoeIzzard** [comment]
Amazing thank you!
