### ISSUE TITLE
Sending more than ~99 lines to Slack fails with too_many_attachments

### ISSUE THREAD

**Issue by justinsteven** [containrrr/shoutrrr#238]
# What happens

When sending 99 lines to Slack, shoutrrr splits on newline and successfully sends it as 99 attachments

When sending 100 lines to Slack, shoutrrr splits on newline and attempts to send it as 100 attachments. This fails with the err "failed to send slack notification: webhook response: too_many_attachments"

Note that in some of my other testing, sending 100 lines succeeds but 101 lines fails. I have an off-by-one error somewhere.

# What is expected

Sending any number of lines to Slack, provided it is within the character limit, succeeds.

# Demo

Using the following harness:

```go
package main

import (
    "fmt"
    "github.com/containrrr/shoutrrr"
    "io"
    "os"
)

func main() {
    if len(os.Args) < 2 {
        fmt.Printf("Usage: %s <url>\n", os.Args[0])
        os.Exit(1)
    }

    url := os.Args[1]

    bufB, err := io.ReadAll(os.Stdin)
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }

    buf := string(bufB)

    err = shoutrrr.Send(url, buf)
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
}
```

Sending 99 lines succeeds:

```plain
% yes | head -n99 | go run shoutrrr_harness.go $URL && echo success
success
```

While sending 100 lines fails:

```plain
% yes | head -n100 | go run shoutrrr_harness.go $URL && echo success
failed to send slack notification: webhook response: too_many_attachments
exit status 1
```

Note that sending 99 relatively long lines still succeeds, indicating this is a problem caused by line count not character count:

```plain
% yes AAAAAAAAAAAAAAAAAAAAAAAAAAA | head -n99 | go run shoutrrr_harness.go $URL && echo success
success
```

**Comment by piksel** [comment]
Thanks for testing these!

**Comment by piksel** [comment]
Also, you can use the shoutrrr CLI (`go install github.com/containrrr/shoutrrr/shoutrrr@latest`) to test it instead of the above harness. You would need to use xargs or a FIFO though, since it does not support reading message from stdin (should be supported in next release though).

**Comment by justinsteven** [comment]
Thanks for that. Being able to feed via stdin was exactly the reason I shied from the CLI, good to hear it's coming soon!

**Comment by piksel** [comment]
@justinsteven ref #243
