### ISSUE TITLE
Telegram private channels cannot be used with @-prefix syntax

### ISSUE THREAD

**Issue by JosephKav** [containrrr/shoutrrr#249]
The docs say that 'Props can be either supplied using the params argument, or through the URL', but when chats/channel isn't declared in the url, you get an `error initializing router services: no channels defined in config URL`
https://containrrr.dev/shoutrrr/v0.5/services/telegram/#queryparam_props

I wasn't sure how exactly to go about doing this. I'd be able to give other places where this may happen a go if I encounter it again (and a PR for this is done)

Also, I'd recommend adding [this](https://github.com/containrrr/shoutrrr/issues/223#issuecomment-1088874341) comment to the docs as it makes getting the channel ID a lot easier! That 't.me/' method didn't work for me.

**Comment by piksel** [comment]
The `params` can be used to override certain settings per message, but if the setting is required, it has to be be configured "globally", or else the initialization logic will complain about it not being specified.

Did you check the link to the dev docs for the updated Chat ID / Channel Name retrieval?
https://containrrr.dev/shoutrrr/dev/services/telegram/#identifying_the_target_chatschannels

t.me/channel is for channel _names_, not _id_s, and those need to be prefixed by `@`.

**Comment by JosephKav** [comment]
> The `params` can be used to override certain settings per message, but if the setting is required, it has to be be configured "globally", or else the initialization logic will complain about it not being specified.

Ah, okay, thanks for letting me know. Would be nice to have this in the docs, but if you don't want to, you can just close this issue

> Did you check the link to the dev docs for the updated Chat ID / Channel Name retrieval? https://containrrr.dev/shoutrrr/dev/services/telegram/#identifying_the_target_chatschannels
> 
> t.me/channel is for channel _names_, not _ids_, and those need to be prefixed by `@`.

Yeah I tried `@+...`, `@...`, `%40+....`%40....` a few times each but none of them worked. (Wasn't sure on that + being part of the ID or not, that's why I tried with and without it). Ended up just forwarding the JSON dumper and getting the ID. That worked first time

**Comment by JosephKav** [comment]
> Instead you get an invite link, but that cannot be used to send messages to. This should definitely be added to the docs. I couldn't get the JsonDumpBot to join a channel, so I don't know how useful it would be. Did you get it to work? The most straight forward way to set it up is to use the `telegram` generator:

You don't need them to join the channel, you can just forward the message to them and look under `message.forward_from_chat.id` in the response it gives. The message doesn't need to contain anything, it just needs to be in the channel you want the ID of

**Comment by piksel** [comment]
(hijacking the issue for the problem discussed above)
