### ISSUE TITLE
Add Pushcut support

### ISSUE THREAD

**Issue by apfelnutzer** [containrrr/shoutrrr#256]
See [Pushcut integration support ](https://www.pushcut.io/support_integrations.html).

**Comment by apfelnutzer** [comment]
I tried to make it work using the generic web hook but didn't manage it... Pushcut returns error code 400 (Bad request) indicating a malformed JSON. I suppose the structure or attributes are not compliant to what Pushcut expects. Unfortunately I did not find a way to increase the log level of Shoutrrr to see the actual request.

**Comment by piksel** [comment]
No, the generic one is generally only suitable for when you can customize how the payload is interpreted on the receiving side.

**Comment by piksel** [comment]
With the added features in #260, Pushcut should actually work with the `generic` service and the `JSON` template:
```
generic://api.pushcut.io/<secret>/notifications/<notification-name>?messagekey=text&template=json
```

**Comment by apfelnutzer** [comment]
Great, I'll try this out later or tomorrow. Is there any documentation or example available on how to use the JSON template?

**Comment by apfelnutzer** [comment]
... just found [this](https://containrrr.dev/shoutrrr/dev/services/generic/) and will give it a try.

**Comment by apfelnutzer** [comment]
@piksel, I'm struggling to build the docker image from the source code (/main): 

```
user@raspberrypi:~/Docker-Builds/shoutrrr $ sudo docker build --no-cache -t shoutrrr/shoutrrr:dev --platform linux/arm/v7 .
Sending build context to Docker daemon  13.31MB
Step 1/6 : FROM alpine:3.11 as alpine
 ---> bbc190d1e1d2
Step 2/6 : RUN apk add --no-cache ca-certificates
 ---> Running in 87e14c9bdcb5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r2)
Executing busybox-1.31.1-r11.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 5 MiB in 15 packages
Removing intermediate container 87e14c9bdcb5
 ---> 28f856bec5df
Step 3/6 : FROM scratch
 ---> 
Step 4/6 : COPY --from=alpine     /etc/ssl/certs/ca-certificates.crt     /etc/ssl/certs/ca-certificates.crt
 ---> 062f5b9ff4ed
Step 5/6 : COPY shoutrrr/shoutrrr /
COPY failed: file not found in build context or excluded by .dockerignore: stat shoutrrr/shoutrrr: file does not exist
```

Any ideas?

**Comment by apfelnutzer** [comment]
... got it: I missed the build step. Next try.

**Comment by apfelnutzer** [comment]
@piksel, newly created container based on /main sources is running, but I still do not receive notifications. Configuration for docker compose is

```
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "generic://api.pushcut.io/<SECRET>/notifications/Watchtower?messagekey=text&template=json"
      WATCHTOWER_NOTIFICATION_TEMPLATE: "{{range .}}{{.Message}}{{println}}{{end}}"
```

Anything wrong here?

**Comment by apfelnutzer** [comment]
Container logs show 

```
2022-07-17T22:10:28.392173286+02:00 exec /shoutrrr: no such file or directory
```

... but Discord notifications are working.

**Comment by apfelnutzer** [comment]
Container keeps restarting... but works in-between (for Discord notification, currently send out every hour).

**Comment by piksel** [comment]
Running it with watchtower is a bit more complicated. You can try it with the shoutrrr image you just built with:
```
docker run shoutrrr/shoutrrr:dev send -u "generic://api.pushcut.io/<SECRET>/notifications/Watchtower?messagekey=text&template=json" -m "Message" -t "Title"
```
For watchtower you would need to change the go.mod to target the branch/commit (maybe @latest works?).
I will soon make another release for shoutrrr and update the watchtower dependency...

**Comment by apfelnutzer** [comment]
Watchtower and Shoutrrr are started from the same docker-compose file, that is they use the same network and "know" each other. So it's probably about the Watchtower version I use (latest docker image). By when are you going to update the Shoutrrr image? I'm wondering if I should just wait for that or try it on my own, building the Watchtower image from the latest  branch...

**Comment by piksel** [comment]
Watchtower uses shoutrrr as a library, compiled in to the binary. It cannot interact with a separate shoutrrr container.
But this change is not even released in shoutrrr, so you would have to build watchtower with a commit tag instead of a version number for the shoutrrr dependency.
I will probably make a release of shoutrrr tomorrow, there should be a watchtower branch that uses the new version sometime then as well, but I can keep you updated.

**Comment by apfelnutzer** [comment]
Ok, thanks. That's new to me and it would explain why I still get notifications although the Shoutrrr container keeps restarting. I set up Watchtower/Shoutrrr a couple of weeks ago using a tutorial and thus thought it would work with different containers.

**Comment by apfelnutzer** [comment]
Just shut down the Shoutrrr container and restarted the Watchtower container: as you said above it send out the notification directly without the Shoutrrr container. Thanks for clarification!

**Comment by piksel** [comment]
@apfelnutzer yeah, those `Dockerfile`s rely on there already being a built `watchtower`/`shoutrrr` binary in the source path, since they are meant for `goreleaser`.
There is [Dockerfile.dev-self-contained](https://github.com/containrrr/watchtower/blob/main/dockerfiles/Dockerfile.dev-self-contained) that should build the binary as well.

Shoutrrr v0.6.1 is released now anyhow, and the PR for updating the dependency is  https://github.com/containrrr/watchtower/pull/1325.

**Comment by apfelnutzer** [comment]
@piksel - Hm: Just noticed that [`go.sum`](https://github.com/containrrr/watchtower/blob/5f8565570c71d74d99dc24411218f6bb00aaf36d/go.sum#L23) on `/main `still refers to version 0.5.3 of shoutrrr - not sure if this is relevant?

```
github.com/containrrr/shoutrrr v0.5.3 h1:ndDN/cKl3cfmuHHjcTDiLTxxjl/1VTWTolOUTLUgiqc=
github.com/containrrr/shoutrrr v0.5.3/go.mod h1:ye9jGX5YzMnJ76waaNVWlJ4luhMEyt1EWU5unYTQSb0=
```

So I have to wait for an update of the official Watchtower image, or I can build it now on my own based on `/main` and use the "self contained" docker files to create the continer, correct?

**Comment by piksel** [comment]
Yeah, that got reverted in a rebase. I have since re-updated it again. It should work now.

**Comment by apfelnutzer** [comment]
May be the two of you should work more closely together ;-)
