### ISSUE TITLE
ntfy support

### ISSUE THREAD

**Issue by mabed-fr** [containrrr/shoutrrr#261]
Hello,

Do you have the possibility to make notifications compatible with ntfy?

It's a light and self-hosting service!
https://ntfy.sh/

Can you consider my request?

Regards

**Comment by piksel** [comment]
Basic support (only a message) should work with the `generic` service, but since the additional properties need to be in headers, it would still require explicit shoutrrr support.

**Comment by MaximilianGaedig** [comment]
+1 on this

**Comment by simskij** [comment]
I'd be fine with adding support for this. Looks like a neat addition, kinda similar to Pushbullet.

**Comment by MaximilianGaedig** [comment]
pushbullet but much better as it's fully FOSS

**Comment by ksurl** [comment]
generic webhook url works if no authentication is required, but need header support for authentication on a selfhosted ntfy server.

**Comment by pavel-pi** [comment]
For anyone with newline issues when base64 encoding: As stated [here](https://superuser.com/a/1225139), a newline is added after 76 characters by default. To overcome this, use `-w 0`.
  
```
echo -n "Basic `echo -n 'testuser:fakepassword' | base64 -w 0`" | base64 -w 0 | tr -d '='
```
