### ISSUE TITLE
smpt notification not working with startTLS enabled

### ISSUE THREAD

**Issue by urbaman** [containrrr/shoutrrr#265]
Hi,

I'm struggling to use the smtp notify system.

I'm using a simple URL:

smtp://user@domain.com:[password@smtpdomain.com](mailto:password@smtpdomain.com):587/?fromAddress=[kured@domain.com](mailto:kured@domain.com)&toAddresses=[user@domain.com](mailto:user@domain.com)

The smtp server is a Plesk system behind Cloudflare DNS (not proxied).

I tried changing the ssl cert of the mail server, both with letsencrypt and cloudflare certs, but I get "the cert is not valid for smtp.domain.com" or "the cert is signed by invalid authority".

Disabling startTLS does not work: it does not authenticate a non-encrypted request.

Using other clients to the same smtp works, enabling "accept all certs", is there a way to properly make this work?

Thank you very much.

**Comment by piksel** [comment]
You could try connecting via openssl with 
```
openssl s_client -starttls smtp smtpdomain.com
```
To see what the certificate problems are. 

The error messages does seem pretty straight forward though; "cert is not valid for" indicates that the DNS names does not match, and the "invalid authority" indicates that the certificate authority is not in the Linux default trusted root CA pool.
Which cert gave what error?
