### ISSUE TITLE
Proposal: Simple + Extended API

### ISSUE THREAD

**Issue by piksel** [containrrr/shoutrrr#3]
Some of the features would greatly benefit from an instance of some kind that can be kept between notification calls.
One of the more obvious ones are the concatination/buffer of notifications that belong to a single session.
Another is the templates which would need to be compiled (and provided/loaded from storage) on every send.
So, what I am proposing is to move the params, logging and "buffer" to some kind of instance that provides the more extended functions and keep `shoutrr.Send()` minimal (only taking a URL + message).

**Comment by piksel** [comment]
Superseded by new service API

**Comment by simskij** [comment]
@all-contributors add @piksel for code and docs and maintenance
