### ISSUE TITLE
Standardize "title" field for services

### ISSUE THREAD

**Issue by onedr0p** [containrrr/shoutrrr#30]
For example, pushover allows you to send a title but it looks like we can only send a message body. Here's the apprise example:

```bash
apprise -t 'my title' -b 'my notification body' \
   'mailto://myemail:mypass@gmail.com' \
   'pbul://o.gn5kj6nfhv736I7jC3cj3QLRiyhgl98b'
```

**Comment by piksel** [comment]
Is the title likely to be dynamic? Wouldn't it be enough to set it in the URL? (Like how subject for smtp works)

**Comment by onedr0p** [comment]
The title could very well be dynamic, and looking at the source code, I can't see how pushover supports sending titles...

**Comment by simskij** [comment]
If I put the watchtower-maintainer-hat , I think dynamic titles might be nice. It would for instance be nice to be able to specify the log level as a title, or something similar.

**Comment by piksel** [comment]
All right, overruled then!

Regarding pushover; no it might not have that field right now, but it can easily be added. Even without changing the API for all services :) But I think it will be fine. I opted to not include specific title handling earlier because only the SMTP service used it.

**Comment by simskij** [comment]
> All right, overruled then!
> 
> 
> 
> Regarding pushover; no it might not have that field right now, but it can easily be added. Even without changing the API for all services :) But I think it will be fine. I opted to not include specific title handling earlier because only the SMTP service used it.

I’m not looking to overrule you. Just weighing in what *might* be beneficial for WT. Shoutrrr is a separate project and Im more than happy to adjust to that. 😅

**Comment by onedr0p** [comment]
> I’m not looking to overrule you.

Agreed, I have a project I have been working on that I would love to use shoutrrr for, but it's lacking in a few things I would like.

I may try to open a PR with some new features :)

**Comment by piksel** [comment]
Oh, btw, this IS actually supported through the `params` argument in the service API. Unfortunately, the service needs to explicitly add the support, and they don't have to use the same name. The only service that supports it AFAIK is SMTP which let's you override the subject per message.

**Comment by andig** [comment]
I would like to support this request. I've started using shoutrrr and started using "title" only to figure out that email expects "subject". I think standardizing would be great and could be done in a backward-compatible way.
