### ISSUE TITLE
Pushover can not be reached over IPv6

### ISSUE THREAD

**Issue by olerap** [containrrr/shoutrrr#305]
Using shoutrrr with Pushover implementation on an IPv6 only VPS.

`time="2022-12-12T16:32:38+01:00" level=error msg="Failed to send shoutrrr notification" error="failed to send using pushover: timed out" index=0 notify=no service=pushover`

Can you please add IPv6 support?

**Comment by piksel** [comment]
When resolving the pushover API domain it returns both IPv4 and IPv6 URLs:
```
> nslookup api.pushover.net
...

Non-authoritative answer:
Name:   api.pushover.net
Address: 45.77.212.87
Name:   api.pushover.net
Address: 45.63.37.132
Name:   api.pushover.net
Address: 137.220.59.207
Name:   api.pushover.net
Address: 2001:19f0:5c00:13ce::2
Name:   api.pushover.net
Address: 2001:19f0:8001:1c96::2
Name:   api.pushover.net
Address: 2001:19f0:8001:1c49::2
```

The go http client (which the pushover service uses) tries to connect to all of the responses (two at the time, with the second one slightly delayed), using the connection to the first that succeeds.
I **think** the problem you are experiencing is that it isn't until the 4th address is tried it would use IPv6, meaning that at least two IPv4 connections would have already timed out.
This accumulates to a combined timeout larger than the total allowed time for sending a notification.
Not sure how to deal with this problem...

**Comment by piksel** [comment]
Hm, actually, the two categories of addresses tested in parallel are grouped based on whether they are IPv4, so the second (with 300ms delay) should be a IPv6 one.
I'm not so sure this is caused by shoutrrr/go's IPv6 support, perhaps it's related to the container networking?

**Comment by olerap** [comment]
Ah, you're right! The container networking wasn't setup properly. I added it to the IPv6 docker network and it's working now. Thanks!
