### ISSUE TITLE
Email alias (XXX+YY@example.com) makes notifications fail silently

### ISSUE THREAD

**Issue by gbip** [containrrr/shoutrrr#306]
*Transferred from containrrr/watchtower, original issue:*

### Describe the bug

I have been using my standard email adress with watchtower with success recently.

However, when using an email alias, watchtower does not send any email at all.

### Steps to reproduce

1. Set the following env variables :
```
WATCHTOWER_NOTIFICATION_REPORT="true"
WATCHTOWER_NOTIFICATION_URL="smtp://@127.0.0.1:25/?fromaddress=watchtower@example.local&toaddresses=email+alias@example.local"
```
2. Launch watchtower :
```
/usr/local/bin/watchtower --monitor-only --no-restart --interval 10 --no-startup-message --notifications-level info --warn-on-head-failure never
```
3. Check your postfix logs and your mailbox => you shall have not received anything

### Expected behavior

Since using an email adress without an alias works, I expect the aliased email adress to work (or at least to generate an error message).

### Environment

Watchtower 1.5.1 running on `"Debian GNU/Linux 11 (bullseye)"`

### Your logs

```text
Here is the relevant part of the log files :

Dec 19 16:28:33 dev-terralego-prnsn2 watchtower[140669]: time="2022-12-19T16:28:33+01:00" level=info msg="Session done" Failed=0 Scanned=14 Updated=1 notify=no
Dec 19 16:28:33 dev-terralego-prnsn2 watchtower[140669]: time="2022-12-19T16:28:33+01:00" level=debug msg="Scheduled next run: 2022-12-19 16:28:42 +0100 CET"
Dec 19 16:28:42 dev-terralego-prnsn2 watchtower[140669]: time="2022-12-19T16:28:42+01:00" level=debug msg="Checking containers for updated images"
```
```

**Comment by piksel** [comment]
As I suspected, this will lead to the SMTP service sending e-mails to addresses with spaces in them. Since those are not valid as per RFC 5322, we should just replace the spaces with `+` again.

**Comment by gbip** [comment]
Thank you !
