### ISSUE TITLE
Support Home Assistant 

### ISSUE THREAD

**Issue by Almighty-Alpaca** [containrrr/shoutrrr#325]
I'd love to see support for sending notifications to a Home Assistant instance.

Documentation: https://www.home-assistant.io/integrations/notify/
Example implementation: https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/home-assistant.js

**Comment by piksel** [comment]
It seems like this would work with the `generic` service with the `template=json` param, apart from the authentication header.  
I have been meaning to add custom header support to it, so perhaps HA wouldn't need it's own service then. 

Instead, we should probably add usage examples for all the targets that are known to work with generic...

**Comment by andriej** [comment]
@piksel can you provide such example for webhook trigger in HA?
I struggle to succesfully deliver any payload to webhook (while all others scripts I use curl with work ok)

**Comment by JeffCrum1** [comment]
I now have it sending to Home Assistant using generic+URL:port/api/webhook/-WebHookID

But, the payload is not JSON formatted even though it does go with the Content-Type: application/json.

The payload looks like:
UNKNOWN HOST IP: '192.168.0.4', MAC: '18:56:80:c7:dd:1e', Hw: 'Intel Corporate'

And, I believe it needs to be like:
{"Title":"UNKNOWN HOST","IP":"192.168.0.4","MAC":"18:56:80:c7:dd:1e","Hw":"Intel Corporate"}

When I send it this way to Home Assistant using curl, the notification works fine.  Using the top payload, Home Assistant throws a JSONDecodeError.

I can't find a way to get Home Assistant to just put out the payload directly.  It seems to need it JSON formatted.

**Comment by JeffCrum1** [comment]
I have it sending to Home Assistant using generic+URL:port/api/webhook/WebHookID

But, the payload must be JSON.  If not, Home Assistant throws a JSONDecodeError.

**Comment by andriej** [comment]
For me calling `generic+URL:port/api/webhook/WebHookID&template=json` doesn't trigger webhook in HA unfortunately

**Comment by JeffCrum1** [comment]
Do you have an automation setup for that webhook?

Can you try this:
Setup new automation
Trigger: Webhook (copy this address for URL:port/api/webhook/WebHookID above)  I did not add template=json.  I think that is default.
Action: Send Notification (to my phone) Message: {{  trigger }}

To test the webhook in HA, I used curl with this:
curl http://192.168.0.104:8123/api/webhook/-ZwmZCSx4et6-4e -H 'Content-Type: application/json'  -d '{"Title":"Title","Data":"Data"}'

If that works, then shoutrrr with a JSON payload should give the same.

Then, in HA, change {{ trigger }} to {{ trigger.json.Title }} - {{ trigger.json.Data }} (change to your payload information) and see if it works.

**Comment by andriej** [comment]
I use https://github.com/aceberg/WatchYourLAN - in config there's place for shoutrrr call.
I've tested - curl query of course triggers the newly made webhook while WAL didn't.
It may be it's fault of WAL in the end

**Comment by JeffCrum1** [comment]
Excellent!

I am trying to do WAL as well.  It is what brought me here.  You can see my closed issue over there (initially for the webhook itself, but now for JSON) with the same info as above.

WAL is not sending JSON.

**Comment by JeffCrum1** [comment]
Okay.  I have been reading both here and at WYL over and over again.  And, I am understanding better now I believe.

When I add template=json to the URL, it gets passed on instead of converting the payload to JSON.

I have verified this using webhook.site.  This is what is received there:
<html>
<body>


https://webhook.site/6853ea21-6140-4664-9ecd-ad8274c?template=json

And, the raw content stays raw.

![image](https://user-images.githubusercontent.com/94788212/222982178-42c0c2d8-eed9-4578-8425-94a9c6762aed.png)

Here is what I am sending:
generic+https://webhook.site/6853ea21-6140-4664-9ecd-ad8274c?template=json

Am I doing this wrong or misunderstanding that shoutrrr should use the template=json to convert the payload to JSON?

**Comment by piksel** [comment]
Don't use `generic+https://`, just use `generic://`. Extra query parameters are just passed through when using the `generic+` helper. It has been proving more confusing than helpful though, so that behaviour should probably be removed in the future...

**Comment by JeffCrum1** [comment]
That is perfect.  Thanks so much for your help.

Just a note, I had to add &disabletls=yes to it as generic:// sends https:// by default.

**Comment by andriej** [comment]
So you got it working with HA and `generic`?

**Comment by JeffCrum1** [comment]
Yes.  The URL in WYL needs to be:
generic://HAIPAddress:HAPort/api/webhook/WebhookIDFromHA?template=json

And, if you need http://
generic://HAIPAddress:HAPort/api/webhook/WebhookIDFromHA?template=json&disabletls=yes

Then, in HA, use {{  trigger.json.message }} to get the message sent from the JSON.

Hope this helps.

**Comment by JeffCrum1** [comment]
> It seems like this would work with the `generic` service with the `template=json` param, apart from the authentication header. I have been meaning to add custom header support to it, so perhaps HA wouldn't need it's own service then.
> 
> Instead, we should probably add usage examples for all the targets that are known to work with generic...

I think I just gave you (with your help!) usage examples for Home Assistant.

I have tried doing forks and pull requests in github and just don't understand it.  SMH.  Old COBOL programmer :)

**Comment by JeffCrum1** [comment]
Just wanted to add that if you use the following in the notification, it'll notify your phone with the message from WYL and a link to your WYL server:
```
service: notify.MyPhoneNameInHA
data:
  message: "A new device has connected to your network: {{  trigger.json.message }}"
  data:
    actions:
      - action: URI
        title: Go to WYL
        uri: http://MyWYLIPAddress:8840
```

**Comment by piksel** [comment]
@JeffCrum1 Yeah, thanks! I added your example to https://containrrr.dev/shoutrrr/0.7/examples/generic/ and linked to your comment (although, I just realized that the URL is not actually converted to a link, I will fix that).

> Old COBOL programmer :)

A rare skill to have these days (and still sought after!)

**Comment by JeffCrum1** [comment]
> @JeffCrum1 Yeah, thanks! I added your example to https://containrrr.dev/shoutrrr/0.7/examples/generic/ and linked to your comment (although, I just realized that the URL is not actually converted to a link, I will fix that).
> 
> > Old COBOL programmer :)
> 
> A rare skill to have these days (and still sought after!)

Thanks so much!

And, yes, we are having a very hard time filling vacancies.  The only people that know it are either old, dying, or dead already.
