### ISSUE TITLE
Matrix: Title is not used

### ISSUE THREAD

**Issue by rad4day** [containrrr/shoutrrr#335]
I am currently trying to configure watchtower to send messages to matrix via shoutrrr.
I use `&title=xyz` as part of the url as stated in the documentation.
The [documentation for the matrix service](https://containrrr.dev/shoutrrr/v0.6/services/matrix/) states that title is a supported property.

Though I can not find it used at all in the source code for the service.
It seems like it is not implemented as running the service CLI doesn't produce a title either?

```
$ docker run --rm -v $PWD/discord-data:/out -it containrrr/shoutrrr:latest send "matrix://watchtower:<pass>@<server>/?title=123" WTF
Notification sent
```
![image](https://user-images.githubusercontent.com/12465878/222977359-c6f7cce5-45c5-4009-a828-841cc653a666.png)

**Comment by piksel** [comment]
No, all services need to support title as a parameter, but matrix does not use it in any way. This should be noted in the docs though. Did you have a certain use for it?

**Comment by rad4day** [comment]
I intended to distinguish between the monitored hosts using the title field.
I solved it now by providing a custom template per host to watchtower :/

I hoped the title was printed somewhere in the message when set.
