### ISSUE TITLE
Add support for XOAUTH2 Authentication for SMTP service

### ISSUE THREAD

**Issue by piksel** [containrrr/shoutrrr#34]
Office365 SMTP does not provide PLAIN authentication, we should either add `LOGIN` authentication support to the SMTP service, or maybe try to implement their custom `XOAUTH2` authentication.

Issue described in: https://github.com/containrrr/watchtower/issues/474

Output from smtp.office365.com:
```
220 LO2P265CA0068.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 12 Apr 2020 13:42:08 +0000
250 SMTPUTF8
EHLO fnizhej
250-LO2P265CA0068.outlook.office365.com Hello [RE.DA.CT.ED]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
```

**Comment by simskij** [comment]
So, it's not the same XOAUTH2 that's used by gmail? 
I'd suggest that we go for the most generic solution in this case.

**Comment by piksel** [comment]
It might be, the X suggests it proprietary (and it's not in the RFC's). But that would be nice.

**Comment by piksel** [comment]
I have successfully sent notifications using a URL generated by Shoutrrr Generate:
![image](https://user-images.githubusercontent.com/807383/83956171-6d738900-a85b-11ea-95eb-e1b73eaf4bb9.png)
(This is for Gmail XOAUTH2, so another generator for Office365 needs to be created, but the foundations are implemented and working)
