### ISSUE TITLE
feature request: ntfy token support

### ISSUE THREAD

**Issue by ksurl** [containrrr/shoutrrr#353]
add support for access tokens: https://docs.ntfy.sh/config/#access-tokens in place of username:password

**Comment by piksel** [comment]
You can simply just omit the username, and it should work I think?

**Comment by MyWay** [comment]
+1 for this

**Comment by cwschulz** [comment]
`ntfy://:token@ntfy.domain/topic` does seem to work for me but I'm unable to get the title to display, only shows a random 12 characters when using `ntfy://:token@ntfy.domain/topic?Title=foo`.  Other params like Tag and Priority do work however.

**Comment by piksel** [comment]
@cwschulz Applications can override the title, which is probably why it's a random string (I'm guessing it's the docker container hostname). If you are using watchtower you can add the `--notification-skip-title` flag to keep the title in the query string.

**Comment by ksurl** [comment]
> `ntfy://:token@ntfy.domain/topic` does seem to work for me but I'm unable to get the title to display, only shows a random 12 characters when using `ntfy://:token@ntfy.domain/topic?Title=foo`.  Other params like Tag and Priority do work however.

Which version are you using and in what app? It was not working when i first opened this issue. Good news if its in the release version now.

**Comment by ksurl** [comment]
this is now supported with https://github.com/containrrr/shoutrrr/pull/377

use generic+https://ntfy.$DOMAIN/topic?@authorization=Bearer+$TOKEN

**Comment by mrjackyliang** [comment]
Can the documentation be updated to show examples on how I can best use this?

I read the implementation and tests and I only have a subset of knowledge on how I can leverage it.

**Comment by piksel** [comment]
Yeah. I plan to add native support for this as well in the `ntfy` service though, so I think that when I get time to work on this I would rather do that.

**Comment by mrjackyliang** [comment]
> Yeah. I plan to add native support for this as well in the `ntfy` service though, so I think that when I get time to work on this I would rather do that.

Awesomeness! Thanks for working on it!!

**Comment by KetchupBomb** [comment]
> > `ntfy://:token@ntfy.domain/topic` does seem to work for me but I'm unable to get the title to display, only shows a random 12 characters when using `ntfy://:token@ntfy.domain/topic?Title=foo`.  Other params like Tag and Priority do work however.
> 
> Which version are you using and in what app? It was not working when i first opened this issue. Good news if its in the release version now.

I was about to make a long post about @cwschulz's [suggestion](https://github.com/containrrr/shoutrrr/issues/353#issuecomment-1722375355) working in [Watchtower](https://docs.ntfy.sh/examples/#watchtower-shoutrrr), but I now think that this issue is probably just missing a commit that enables this feature, because even using shoutrrr directly works:

```
$ docker run -it --rm containrrr/shoutrrr --version
shoutrrr version 0.8.0

$ docker run -it --rm containrrr/shoutrrr send -u ntfy://:tk_3fxREDACTED@ntfy.DOMAIN/TOPIC -m 'shoutrrr CLI'
Notification sent
```

I didn't see anything in the [Ntfy service documentation](https://containrrr.dev/shoutrrr/v0.8/services/ntfy/) about tokens being supported. A surprise, to be sure, but a welcome one
