### ISSUE TITLE
[Feature Request]Add proxy option while sending messages

### ISSUE THREAD

**Issue by leopku** [containrrr/shoutrrr#36]
Firstly, thanks for this awesome package.

While invoking `shoutrrr.Send` or `sender.Send`, can there add an option for setting `http` or `socks5` proxy?

Big thanks.

**Comment by simskij** [comment]
@piksel and @arnested, any thoughts on this? :)

**Comment by piksel** [comment]
The Go [HTTP library respects](https://golang.org/pkg/net/http/#RoundTripper) the https_proxy environment variable, so this doesn't seem like something we would need to implement in the library itself. Do you have a use case where that isn't enough?

For Socks5, you can set it to `socks5://proxy.example.com` for example.

**Comment by leopku** [comment]
> The Go HTTP library [respects the https_proxy environment variable](https://golang.org/pkg/net/http/#RoundTripper), so this doesn't seem like something we would need to implement in the library itself. Do you have a use case where that isn't enough?
> 
> For Socks5, you can set it to `socks5://proxy.example.com` for example.

Thanks a lot.

**Comment by leopku** [comment]
Sorry for reopening.
I'm using shoutrrr as a go library, so I need specify proxy by programming.

**Comment by piksel** [comment]
No worries, if you still have the problem then the issue shouldn't be closed.  

You can change the transport for the default `net/http/Client` and add your proxy to it. All subsequent `http.Get/Post/...` requests will use that proxy.  

I made a  [basic example](https://gist.github.com/piksel/e3a8b8cffdac0d7513c722c6e29fdafd)  using a local SOCKS5 proxy on port 1337 showing how to do it.

**Comment by leopku** [comment]
> No worries, if you still have the problem then the issue shouldn't be closed.
> 
> You can change the transport for the default `net/http/Client` and add your proxy to it. All subsequent `http.Get/Post/...` requests will use that proxy.
> 
> I made a [basic example](https://gist.github.com/piksel/e3a8b8cffdac0d7513c722c6e29fdafd) using a local SOCKS5 proxy on port 1337 showing how to do it.

Big thanks.

**Comment by simskij** [comment]
@piksel maybe it would be beneficial of that example was part of the docs? 🙌🏼🙏🏼
