### ISSUE TITLE
Generic Webhook: Support arbitrary headers

### ISSUE THREAD

**Issue by ThinkChaos** [containrrr/shoutrrr#365]
My use case is to authenticate against the server as currently shoutrrr only supports basic auth, which I'd like to avoid.  
Providing arbitrary headers would also make the feature much more flexible and future proof.

Maybe any param following a specific format could be interpreted as a header?  
For instance: `?hdr_authorization=...`

**Comment by piksel** [comment]
Yeah, this is really should be added. I am thinking that some other character prefix could work, like `?@authorization=` or perhaps `?header:authorization=`?
