### ISSUE TITLE
Generic Webhook: params code doesn't match docs

### ISSUE THREAD

**Issue by ThinkChaos** [containrrr/shoutrrr#366]
The docs say:
> All query variables that are not listed in the [Query/Param Props](https://containrrr.dev/shoutrrr/0.7/services/generic/#queryparam_props) section will be forwarded to the target endpoint

Pretty much none of this is accurate :neutral_face:  
The only case where the params are forwarded is when using the JSON template. And even then, it's not just the ones that "are not listed in the Query/Param Props", it's every single one! Additionally, they are forwarded in the JSON object, not as query args.

I'd be willing to make a PR to fix this, but given that PRs with simple doc fixes haven't been merged lately I don't want to spend any more time on this (already lost a couple hours because of the docs).  
If you are interested in reviewing and merging a fix, please let me know and I'll gladly write some code.

**Comment by piksel** [comment]
Hello. Sorry, could you give an example of how you are using this? If it's through some other software, what versions etc.
Everything in the URL query should be forwarded unless it matches the supported configuration keys.

**Comment by piksel** [comment]
It sounds like you are passing the key-value pairs to the params argument in Send(). That is not meant to be used for service-specific params. Put the query params in the config URL and it should work as documented. The only param you would want to pass in the params argument to the Send methods is probably `title`. This is not a great API, and has organically grown to be that way through usage and demands. The 1.0 release of shoutrrr will probably replace the `params` with just `title`.

**Comment by ThinkChaos** [comment]
Thanks for the reply!

I'm indeed using an app: [Argus](https://release-argus.io) ([relevant docs](https://release-argus.io/docs/config/notify/)). It supports templating its custom data in `params` but not the URL, so I've been using props.

> That is not meant to be used for service-specific params. Put the query params in the config URL and it should work as documented

The docs say otherwise:
> Props can be either supplied using the params argument, or through the URL using `?key=value&key=value` etc.
---
> This is not a great API, and has organically grown to be that way through usage and demands. The 1.0 release of shoutrrr will probably replace the params with just title.

I think that'd be a usability loss because writing things in a map is much clearer and easier (no escaping) compared to URL query args.  
What about keeping support for both, but ensuring there's never a difference between setting a value in the args or props?  
The only nuance would be which overrides the other. To me it seems the URL query should win since replacing something hardcoded in the URL would be confusing.  
This doesn't seem too hard too implement using the existing `PropKeyResolver`.

Would you be interested in a PR to make the props and query args match that described behavior?

**Comment by piksel** [comment]
Yeah, well, the generic service is a special case just because it's... well generic. For all other services, supplying an unknown param is a configuration error. This instead just keeps any unknown parts of the URL and passes it to the upstream service. 

So the docs are correct in that props can be supplied in any way, it's just that the extra query variables are not valid props. The propkey resolver will also not work for this reason, there are no configuration keys for any custom variables. 

We could still allow the upstream query variables to be set using props, but I would prefer a special syntax for this to explicitly show what would be set as a query variable, and what changes the behaviour of the service...

**Comment by ThinkChaos** [comment]
I understand your point and the technical reasons, but as a user the current experience is not good. The special case should at least have special docs.

> to explicitly show what would be set as a query variable, and what changes the behaviour of the service

I agree. Also it would be nice if the format is future proof and could solve stuff like #365. 
Trying to get a feel for what solution would work:  
Does the `PropKeyResolver` support having a fields that's a `map`? I couldn't tell from a quick look, and a map seems like the best fit here.  

Here's a quick idea:
```go
struct{
	PropA int `key:"prop-a"`
	QueryArgs url.Values `key:"q"`
	Headers map[string]string `key:"h"` // or maybe map[string][]string
}
```
Would match:
- these props: `{"prop-a": 1, "q": {"b": ["1"]}, "h": {"c": "2"}}`
- this query: `?prop-a=0&q[b]=1&hdr[c]=2`
  The `x[y]=z` syntax is relatively common on the web and seems like a good match.  
  For arrays, just repeat the query arg name: `q[x]=a&q[x]=b` -> `["a", "b"]`  
  Not sure if it would be needed, but resetting an array could be possible: `q[x]=a&q[x]=&q[x]=b` -> `["b"]` (if someone finds a use case later)

BTW you might be interested in the [mapstructure](https://github.com/mitchellh/mapstructure) and/or [defaults](https://pkg.go.dev/github.com/creasty/defaults) modules as, based on my current understanding, I think they could help simplify the code here.

**Comment by piksel** [comment]
Well, it supports maps, but with another syntax. But that's fine. The main reason that I wrote it was to make simple mapping from key/value-pairs to structs less error-prone. For special case like this, it can be done manually. If we want to use the built in support it would have to be something like: `query=key1:value1,key2:value2` as the key is presumed to always match one struct entry.
