### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by gwenvador** [containrrr/shoutrrr#37]
With the recent integration with containrrr/watchtower is there a docker version of shoutrrr?

**Comment by simskij** [comment]
Hi, and thank you for the report!

Currently, there isn't, but we probably should have a docker image containing the standalone client. 👍

**Comment by simskij** [comment]
Hey!

This just went up on DockerHub! As there is currently no HTTP server built-in, I guess the use case will be somewhat limited unless you place it on a shared volume to be used by some other container, which should be totally doable as it's compiled with CGO disabled.

https://hub.docker.com/repository/docker/containrrr/shoutrrr

Best,
Simme
