### ISSUE TITLE
telegram link preview disable (?preview=false) not working

### ISSUE THREAD

**Issue by hugalafutro** [containrrr/shoutrrr#421]
Hi,

this is the line I use in my docker-compose.yml
`WATCHTOWER_NOTIFICATION_URL=telegram://${TELE_TOKEN}@telegram?chats=${TELE_CHATID}?preview=false`

this is the message with the link preview still enabled I receive:
![image](https://github.com/containrrr/shoutrrr/assets/30209689/c06398a3-b8d2-48c1-b14a-9acbce68ad42)

What am I doing wrong? 
Thanks for any insights!

**Comment by piksel** [comment]
Replace second `?` with a `&` in the URL.

**Comment by hugalafutro** [comment]
Many thanks! that was it!
