### ISSUE TITLE
Issue with telegram format: first path segment in URL cannot contain colon\n

### ISSUE THREAD

**Issue by oscargb1** [containrrr/shoutrrr#45]
I'm using the Shoutrrr integration in Watchtower to send notifications via Telegram, but it seems the format of the notification URL that I'm using isn't correct, as it's giving me the following issue:

`time="2020-06-07T02:33:26+02:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"\\\"telegram://<bot_token>@telegram?channels=<chat_id>\\\"\": first path segment in URL cannot contain colon\n"`

As there isn't a detailed documentation for the Telegram notification, can you tell me if I'm using the correct format?

**Comment by piksel** [comment]
I think you need a slash between `@telegram` and `?channel`:
```
telegram://<bot_token>@telegram/?channels=<chat_id>
```

**Comment by oscargb1** [comment]
Yeah, I noticed that on the telegram tests. But it's still giving me the issue with that change.

**Comment by simskij** [comment]
Could you please paste the full docker run command you're using, but replace the right hand of your token with `mock-token`?

I'm unable to reproduce your error, even without putting a `/` before the `?`

**Comment by oscargb1** [comment]
I'm using docker compose:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
     - WATCHTOWER_NOTIFICATIONS=shoutrrr
     - WATCHTOWER_NOTIFICATION_URL="telegram://632861895:mock-token@telegram/?channels=618771099"
     - TZ=Europe/Madrid
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --interval 3600 --cleanup

**Comment by simskij** [comment]
Ah! You need to change your yaml 😅 

Either:
```yaml
- WATCHTOWER_NOTIFICATION_URL=telegram://632861895:mock-token@telegram/?channels=618771099
```

or
```yaml
  WATCHTOWER_NOTIFICATION_UR: "telegram://632861895:mock-token@telegram/?channels=618771099"
```

**Comment by oscargb1** [comment]
Oops 🙈. Sorry I'm new to Docker.
Thank you so much for the help, now it works!
