### ISSUE TITLE
MS Teams notifications

### ISSUE THREAD

**Issue by diogoduartec** [containrrr/shoutrrr#49]
How can I get this tokens from MS Teams webhook url?

![image](https://user-images.githubusercontent.com/31852339/86150495-77d81a00-bacb-11ea-97fd-21635d29c15a.png)

**Comment by piksel** [comment]
There is a guide in the [microsoft teams documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#setting-up-a-custom-incoming-webhook).

**Comment by simskij** [comment]
docs added in a9206f0
