### ISSUE TITLE
String pipes

### ISSUE THREAD

**Issue by PssbleTrngle** [containrrr/shoutrrr#50]
Is there a way I can use pipes to transform variables
```golang
"{{ .Level | strings.ToUpper }}"
```

**Comment by piksel** [comment]
Yeah, the templates are just [go templates](https://golang.org/pkg/text/template/). It doesn't matter much, but the this template transform is done by Watchtower before it reaches Shoutrrr. I am watching both repos tho :)

**Comment by PssbleTrngle** [comment]
So what you mean ist that the support for these string functions would have to be added to watchtower and not shoutrrr?

**Comment by piksel** [comment]
Yeah, Shoutrrr does have templates as well, but those do not contain ".Level" etc. as  those are watchtower (actually logrus) fields.

**Comment by PssbleTrngle** [comment]
Makes sense, then opening an issue in the watchtower repo would be better

**Comment by PssbleTrngle** [comment]
I have opened one there:  https://github.com/containrrr/watchtower/issues/592
