### ISSUE TITLE
Discord embeds in message

### ISSUE THREAD

**Issue by PssbleTrngle** [containrrr/shoutrrr#51]
Is it possible to send [embedded messages](https://birdie0.github.io/discord-webhooks-guide/structure/embeds.html) to a discord webhook?

The template
```go
{{`{`}}"embeds":[{{range .}} {{`{`}}"title":"{{ .Level }}", "description":"{{ .Message }}" {{`}`}}{{print}}{{end}}]{{`}`}}
```
generates messages in the JSON format
```json
{"embeds":[ {"title":"info", "description":"Starting Watchtower and scheduling first run: 2020-06-30 22:03:31 +0000 UTC m=+300.065202141" }]}
```
But they are just shown as the text value, not actually used by discord

**Comment by PssbleTrngle** [comment]
It would be nice if you could define the content type, as setting it to `application/json` would solve it

**Comment by simskij** [comment]
Great idea! Would you like to have a stab at it yourself? I'd be happy to provide assistance with code reviewing and such. I see no reason why the discord service couldn't have `application/json` as it's default content type.

**Comment by PssbleTrngle** [comment]
I can give it a try, but I have never worked with Go before, so I can't promise anything.
I don't know if setting the default type of discord messages to ``application/json` would be a good idea, as user which would only want to sent plain text messages would have a harder time doing so.

It's not impossible, but plain text messages would have to be sent as
```json
{
  "content": "plain text here"
}
```

**Comment by simskij** [comment]
Fair point. Maybe @piksel has some idea on how to do this?

**Comment by PssbleTrngle** [comment]
Seems like the content type for discord is already set to `application/json`, but the parsed template is put as a string into the `Text` key in the json

https://github.com/containrrr/shoutrrr/blob/6520e5d4be187b31dd14f460147f24e53b4ef42c/pkg/services/discord/discord_json.go#L22

**Comment by PssbleTrngle** [comment]
An parameter notifying wether the given message is already a stringified json object or plain text could be a solution

**Comment by PssbleTrngle** [comment]
The pull request is a version where appending `/json` to the discord service url will send the given message as a JSON object instead of plain text

**Comment by piksel** [comment]
That would work. Maybe we should use something like "/raw" instead, since it's effectively overriding the default JSON body with the message?

**Comment by PssbleTrngle** [comment]
I agree, that would be a better name.
Right now some tests are failing because they are expecting the discord service to throw an error when being supplied with an url that has a path appended.

**Comment by PssbleTrngle** [comment]
I am looking at the defined tests and I was wondering if the maximum length of 100 characters is given by discord?

**Comment by PssbleTrngle** [comment]
I have modified the the test and added new ones for testing wether the JSON flag in the service config is set correctly depending on the given url, they all succeed now

**Comment by piksel** [comment]
I'm not sure where you are seeing the 100 character maximum. The limit is [2000 characters](https://discord.com/developers/docs/resources/webhook#execute-webhook) and that is what is defined at [pkg/services/discord/discord.go#L22](https://github.com/containrrr/shoutrrr/blob/6520e5d4be187b31dd14f460147f24e53b4ef42c/pkg/services/discord/discord.go#L22).

**Comment by PssbleTrngle** [comment]
I was looking at this test
https://github.com/containrrr/shoutrrr/blob/6520e5d4be187b31dd14f460147f24e53b4ef42c/pkg/services/discord/discord_test.go#L73

**Comment by PssbleTrngle** [comment]
Ok, just realised the string is appended 42 times making it longer than 2000 characters, I was just looking at the number 100

**Comment by simskij** [comment]
Just had to comment here that I still am waaay too proud over that hundred char long string 😅

**Comment by piksel** [comment]
Closing this since the branch was merged!
