### ISSUE TITLE
[Feature request] Add support for implicit TLS (port 465) for SMTP

### ISSUE THREAD

**Issue by whalehub** [containrrr/shoutrrr#68]
I tried using shoutrrr with an SMTP URL that's using implicit TLS (port 465) earlier today and observed that the request timed out after a while. The same URL worked fine when using explicit TLS on port 587 via STARTTLS.

**Comment by piksel** [comment]
It shouldn't be too hard to add support for this. Ideally we should always use TLS on port 465, but unfortunately the first service I tried to test this with (mailtrap.io in this case) doesn't use implicit TLS on that port.
So to make this configurable, it seems necessary to add an "ImplicitTLS" enum, that defaults to "Auto" (based on port number) but can be forced on or off.
