### ISSUE TITLE
Add support for MQTT (Home Assistant)

### ISSUE THREAD

**Issue by simskij** [containrrr/shoutrrr#86]
As requested in https://github.com/containrrr/watchtower/issues/618#issuecomment-703123815, we should consider adding support for sending notifications to home assistant. I'm not sure exactly how, or if, this will work, so some investigation will be needed unless someone has a clear idea.

**Comment by dougle03** [comment]
MQTT messaging perhaps?

**Comment by rirofal** [comment]
As mentioned here...

https://github.com/containrrr/watchtower/discussions/676

**Comment by simskij** [comment]
What would be the use case of this? For instance, which lovelace panel would you use to visualize the messages you receive? As a home assistant user myself, I kind of fail to figure out how this would be used. 😅

**Comment by Morphy99** [comment]
> What would be the use case of this? For instance, which lovelace panel would you use to visualize the messages you receive? As a home assistant user myself, I kind of fail to figure out how this would be used.

I use Home Assistant in a docker container and I use Watchtower to update HA and other containers. It would be nice to get notifications when there is an image update available. I use HA mobile companion for my notifications so it would be good to get it through that.

**Comment by es-arif** [comment]
I'm also in the same boat as @Morphy99.
HA user looking at Watchtower.

_I don't think MQTT is the right choice though._

MQTT is no longer built in to Home Assistant core (as far as I recall) and adding another messaging protocol to this project that supports HTTP doesn't make much sense for maintenance, development, and direction (I will assume).

If you wanted notifications from `shoutrrr` to be detected on a micro-sensor that needs MQTT for the bandwidth/size then sure, but seems like everyone here is echoing that we want `Shoutrrr` to reach Home Assistant core for automation and notifications.

[Creating a webhook is trivial](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger) and pairing that with a quick template to [forward the webhook as an action to notify](https://www.home-assistant.io/docs/automation/action/) is also very simple and versatile.

Once you get this `Shoutrrr` message through to HA, you can chop and change the action to [whatever notification service you please](https://www.home-assistant.io/integrations/#notifications).

If this is an internal service, then by default no authentication is required on the webhook which further simplifies things.

I'm very fresh but I will be looking at how to pass a generic POST for the moment, but if a PR is required I will come back and give that ago.

**Comment by fanuch** [comment]
I'm also in the same boat as @Morphy99.
HA user looking at Watchtower.

_I don't think MQTT is the right choice though._

MQTT is no longer built in to Home Assistant core (as far as I recall) and adding another messaging protocol to this project that supports HTTP doesn't make much sense for maintenance, development, and direction (I will assume).

If you wanted notifications from `shoutrrr` to be detected on a micro-sensor that needs MQTT for the bandwidth/size then sure, but seems like everyone here is echoing that we want `Shoutrrr` to reach Home Assistant core for automation and notifications.

[Creating a webhook is trivial](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger) and pairing that with a quick template to [forward the webhook as an action to notify](https://www.home-assistant.io/docs/automation/action/) is also very simple and versatile.

Once you get this `Shoutrrr` message through to HA, you can chop and change the action to [whatever notification service you please](https://www.home-assistant.io/integrations/#notifications).

If this is an internal service, then by default no authentication is required on the webhook which further simplifies things.

I'm very fresh but I will be looking at how to pass a generic POST for the moment, but if a PR is required I will come back and give that ago.

**Comment by HeedfulCrayon** [comment]
I would agree with @fanuch on this one.  I have tried testing the generic method with shoutrrr, and it doesn't seem to do a post, which is where the enhancement would be needed for home assistant since GET requests do not work for their webhook automations

**Comment by piksel** [comment]
@HeedfulCrayon Generic *does* use POST:
https://github.com/containrrr/shoutrrr/blob/a68a9b1a8cf588a7190f896fe0a4833f128957f3/pkg/services/generic/generic.go#L67

**Comment by simskij** [comment]
As this is already covered from what I can tell, I'm closing this issue. Feel free to open new ones if needed.
