### ISSUE TITLE
Almost no services implements params overrides

### ISSUE THREAD

**Issue by atighineanu** [containrrr/shoutrrr#88]
So, I tried to test the sender creation feature. 
The code looks like this:
```
url := "slack://A/B/C"
	sender, err := shoutrrr.CreateSender(url)
	if err != nil {
		fmt.Printf("%v", err)
	}
	var hej_da types.Params
	hej_da = make(map[string]string)
	hej_da["channel"] = "random"
	sender.Send("tralala", &hej_da)
```
NOTE: I have created the "random" channel and added the bot to it. Still, when adding the params to the sender, it still didn't send the message to the desired "random" channel. Instead, it sent it to the one corresponding to one of the tokens (I guess it must be C, not sure).

**Comment by piksel** [comment]
Yeah, the `Params` overrides need to implemented in every service, and I think `SMTP` might be the only service that fully implements it.
Slack, like you used in your code above, does not handle them at all:
https://github.com/containrrr/shoutrrr/blob/78573859356243fb2ba448dd9331fa6a06baafda/pkg/services/slack/slack.go#L27

There should be a generic solution for all services to use by just adding a tag to their config.
