### ISSUE TITLE
Add support for Discord

### ISSUE THREAD

**Issue by andig** [containrrr/shoutrrr#89]
There‘s already a golang library at https://github.com/bwmarrin/discordgo

**Comment by piksel** [comment]
Yeah, I've been messing with the API recently, shouldn't be too hard to add.

**Comment by piksel** [comment]
Wait, we already have discord support?

https://containrrr.dev/shoutrrr/services/discord/

**Comment by andig** [comment]
Whaaaat, didn‘t even notice :O

**Comment by simskij** [comment]
😂
