### ISSUE TITLE
Add mattermost

### ISSUE THREAD

**Issue by mblaschke** [containrrr/shoutrrr#9]
Mattermost is similar to Slack but runs on premise so it needs a hostname per notification.

**Comment by simskij** [comment]
Hey there! Welcome! 👋🏼 Sounds reasonable. Would you like to have a stab at it yourself?

**Comment by simskij** [comment]
Added in https://github.com/containrrr/shoutrrr/commit/f17c3e27d07ac823359a5153b06ed3c1bc7ee0bc, which is a manual merge of #11

**Comment by simskij** [comment]
@all-contributors add @amirschnell for code
