### ISSUE TITLE
mattermost: segfault in mattermost.(*Service).Send

### ISSUE THREAD

**Issue by dholbach** [containrrr/shoutrrr#93]
As a follow-up to https://github.com/weaveworks/kured/pull/228 I'm seeing the following issue:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x133fc8c]
goroutine 23 [running]:
github.com/containrrr/shoutrrr/pkg/services/mattermost.(*Service).Send(0xc000733760, 0xc0008f0520, 0x17, 0xc0000f5a50, 0xc000733760, 0x0)
    /home/daniel/go/pkg/mod/github.com/containrrr/shoutrrr@v0.0.0-20201124203606-785738593562/pkg/services/mattermost/mattermost.go:38 +0x20c
github.com/containrrr/shoutrrr.Send(0x7ffe86674bad, 0x35, 0xc0008f0520, 0x17, 0x1, 0xc0008f0520)
    /home/daniel/go/pkg/mod/github.com/containrrr/shoutrrr@v0.0.0-20201124203606-785738593562/shoutrrr.go:24 +0xcd
main.commandReboot(0xc00003e02e, 0x8)
    /home/daniel/dev/kured/cmd/kured/main.go:313 +0x280
main.rebootAsRequired(0xc00003e02e, 0x8, 0xc00046ca00, 0x0)
    /home/daniel/dev/kured/cmd/kured/main.go:380 +0x523
created by main.root
    /home/daniel/dev/kured/cmd/kured/main.go:414 +0x637
```

This is with `mattermost://<host>/<token>`. The first message get through perfectly. The code uses `shoutrrr.send` (cc @atighineanu). 

This is with minikube 1.15.1 and k8s 1.19.4.

**Comment by atighineanu** [comment]
That's interesting, since I've tested it with kind and it worked fine. However, on minikube it fails. I am going to work on this, if that's okay with everyone.

**Comment by piksel** [comment]
The response is checked without first checking if it returned an error:
https://github.com/containrrr/shoutrrr/blob/78573859356243fb2ba448dd9331fa6a06baafda/pkg/services/mattermost/mattermost.go#L36-L41

**Comment by atighineanu** [comment]
> The response is checked without first checking if it returned an error:
> https://github.com/containrrr/shoutrrr/blob/78573859356243fb2ba448dd9331fa6a06baafda/pkg/services/mattermost/mattermost.go#L36-L41
> 
> So there is probably something else going on that causes it to fail, but fixing this would at least return the correct error instead of panicking.
> I guess the response body should be closed as well instead of letting the GC handle it.

yeah. Tested it. It looks like minikube workers are isolated from outer world.

**Comment by dholbach** [comment]
Great work fixing this!
