### ISSUE TITLE
Add generic webhook service

### ISSUE THREAD

**Issue by piksel** [containrrr/shoutrrr#97]
Most webhooks need a specific payload to be sent to them. That is one of the main purposes of the templates that services can use.  

If you are consuming shoutrrr "directly" without exposing it's URLs to the end user to configure, it's pretty trivial to support, so initially this is the only supported method (if consumers want to support them, they would need to load the templates manually).

**Comment by vajonam** [comment]
My use case is to have shoutrr notify home assistant or node red with changes so then I can act on that, send a push or restart other things etc. Looking forward to just a webhook with a default playload that shows up in email in a json format.

**Comment by piksel** [comment]
@vajonam I don't think I understand what you mean by
> default playload that shows up in email in a json format.

Could you show an example of the payload you would expect?

**Comment by phipolis** [comment]
@piksel My interpretation of what @vajonam meant was a JSON blob roughly corresponding to the smtp service: from, subject, and message. 

It could be more basic still. As you can see from the [Home-assistant webhook-trigger docs](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger), it's an extremely simple unauthenticated API. The JSON payload is passed along and the owner can use the keys as they like. 

So the format shoutrrr uses is flexible. Perhaps:
`shoutrr send https://your-home-assistant:8123/api/webhook/some_hook_id "Important information"`
could be equivalent to
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"message":"Important information"}' \
  https://your-home-assistant:8123/api/webhook/some_hook_id
```

**Comment by blaxer** [comment]
What Phipolis is proposing would be great. I have been "impersonating" slack via nodered for a long time now in order to receive notifications from watchtower. Since watchtower switched to shoutrrr this has been broken. A generic webhook that can be used locally and does not reach out to any commercially hosted solutions would be ideal for those of us that are #selfhosted using nodered or home assistant.

**Comment by vajonam** [comment]
> @vajonam I don't think I understand what you mean by
> 
> > default playload that shows up in email in a json format.
> 
> Could you show an example of the payload you would expect?

@piksel  to add on to what @phipolis proposed. the data would be a JSON like

```
{
  "message": [
    {
      "plex": [
        "Fouund new image",
        "restarting",
        "cleaning up"
      ]
    },
    {
      "sonarr": [
        "Fouund new image",
        "restarting",
        "cleaning up"
      ]
    }
  ]
}
```

basically gives us some infromation about which containers have been updated, restarted, cleaned up etc. Whatever gets sent to the email client can show up in a parse able json format.

**Comment by piksel** [comment]
Ah, I see. Yeah, this is actually not the what the generic webhook service is meant for, but it's a really good addition.

I would suggest that this is added as a `shoutrrr` service. As the syntax/payload is defined by shoutrrr and not another service.
The payload would roughly be:

```json
{
  "title":  "Title",
  "messages": [
    {
      "text": "Message 1 ",
      "time": "2021-01-14T22:25:58.595Z",
      "level": "Info",
      "params": {
          "msg_key1": "msg_value1"
      }
    }, {
      "text": "Message 2 ",
      "time": "2021-01-14T22:25:59.595Z",
      "level": "Warning"
    }
  ],
  "params": {
    "key1": "value1"
  }
}
```

Params for the payload would be customizable by putting the key/values in the configuration URL, like:
`shoutrrr+https://myserver.tld:8081/?key1=value`

And the message params would most likely include logrus extra fields if sent from watchtower.

---

Also, for completeness; the generic webhook service is meant to be a way to define the payload by using a template. Which is, kind of, the other way around.

**Comment by phipolis** [comment]
@piksel Oops, I think I/we misinterpreted this issue :sweat_smile: Sorry to hijack. Should a new issue be created then?

**Comment by piksel** [comment]
I guess it would be easier to create a new issue for the template service instead, as this contains relevant conversation.

**Comment by paulfwilliams** [comment]
I posted this as a [feature request](https://github.com/containrrr/watchtower/discussions/843) on the watchtower hub.

My company uses RingCentral (the Glip application) for team messaging. RingCentral supports incoming hooks from several different applications. We have some apps (Jenkins builds, for example) hooked up with notifications already.

I am currently adding Watchtower support for some containers we need updated frequently. I would like to be able to send notifications from Watchtower to the RingCentral Glip application, so my developer group knows when containers have been updated.

RingCentral exposes a generic webhook interface with a definition like:

POST https://hooks.glip.com/webhook/...144 character base 64 encoded identifier...
Content-Type: application/json

{
"activity": "Watchtower Notification",
"iconUri": "https://containrrr.dev/watchtower/images/logo-450px.png",
"title": "post title",
"text": "post text"
}

**Comment by DoTheEvo** [comment]
Could we get actual fully write up example of generic webhook? 
I am using signal-cli-rest-api and its working fine with this executed

     curl -X POST -H "Content-Type: application/json" "https://signal.example.com/v2/send" -d '{"message": "Test blablabla", "number": "+421999999999", "recipients": [ "+421999999999" ]}'

Am I able to use this with shoutrrr generic webhook?
